### ISSUE TITLE
Is there a way to print javabean in a pretty way?

### ISSUE THREAD

**Issue by ghuiii** [orhanobut/logger#118]
Below is a toString method of a model.
![image](https://cloud.githubusercontent.com/assets/5203798/25740515/701a8c24-31b9-11e7-8fc3-3bcce2251748.png)

If I use ``Logger.d("topicInfo: " + topicInfo)``, the output is : 

![image](https://cloud.githubusercontent.com/assets/5203798/25740395/f4218d8e-31b8-11e7-8f28-75bbd7f5a6ed.png)

You can see the output is out of order。Is there a way to solve this.

> PS: I know to add '\n' manually to the toString method.

**Comment by orhanobut** [comment]
That'd be a little difficult since Logger.d depends on toString() if the object is not any collection type. There could be an implementation that goes through all the fields and for each fields go through recursively but that is overkill. As you already mentioned yourself, I think best way to handle this in toString method by adding '\n' manually. I can't think any other approach that can solve this gracefully.
