### ISSUE TITLE
the same name as java.util.logging ,

### ISSUE THREAD

**Issue by lqjymt** [orhanobut/logger#97]
because the same name as java.util.logging.Logger,i cann't  find  the  method Logger.d();just  because i have import the error  package.what fuck.may other don't have the same problem with me.

**Comment by orhanobut** [comment]
You have 2 options

1. You can wrap Logger and give a different name and use it along with other Logger
2. You can use one of them with package name com.orhanobut.Logger.d(

But I wouldn't advise to use both of them at the same to be honest, not sure why you need both at the same though. But if you must, I'd advise to create an abstraction and use the abstract class in all your code base, otherwise you will be super decoupled with both of them
